- readme.md
[Github Review Steps](https://app.gitkraken.com/glo/card/852a557fee1b4a8e905d232bea5f0d8c)
> [COD-13]updated readme for reviews

- client/src/components/About.js
- client/src/components/App.js
- client/src/styles/About.css
[Create an about summary](https://app.gitkraken.com/glo/card/7728327b9a3b47c08bb4d1e163066668)
> [COD-4] added new about information and updated styles with a new look

- client/src/components/Slack.js
updated slack link to new channel
> [COD-15] updated slack link

- client/src/components/Nav.js
- client/src/styles/ContactForm.scss
- client/src/styles/Nav.scss
- client/src/styles/Slack.scss
- Added onclick for logo
- Resized logo and had to change media query since logo was bigger
- Slack logo wasn't centered
- Adjusted media query for contact form
> [COD-20] logo click

- client/src/components/App.js
- client/src/components/Home.js
- client/src/components/Utilities.js
- client/src/components/utilities/Randomizer.js
- client/src/components/utilities/Timer.js
- client/src/styles/Main.scss
- client/src/styles/Randomizer.scss
- client/src/styles/Timer.scss
- client/src/styles/Utilities.scss
[COD-22] 
Just needs to link to the other utilities.
Also, added some basic styles to randomizer and timer, so they weren't covered by the navbar. Moved randomizer styles to Main.scss as an import.
> [COD-22] Update Utilities Page

- client/src/components/App.js
- client/src/components/Home.js
- client/src/components/Utilities.js
- client/src/components/utilities/Randomizer.js
- client/src/components/utilities/Timer.js
- client/src/styles/Main.scss
- client/src/styles/Randomizer.scss
- client/src/styles/Timer.scss
**Make sure pull-request for COD-22 is completed first**
changed form submit for timer to always set isRunning to true, fixes issue #23
> [Issue#23] fixed Timer pause before cancel

- client/src/components/utilities/Timer.js
created middle-man variable timeInSec to error check against for form validation. Resolves issue #30
> [issue#30] Very Cool Timer Bug

- client/src/components/About.js
- client/src/components/ContactForm.js
- client/src/components/Slack.js
- client/src/components/UpcomingEvents.js
- client/src/components/nav/HomeLinks.js
- client/src/components/nav/Nav.js
- client/src/components/nav/UtilitiesLinks.js
- client/src/styles/About.scss
- client/src/styles/ContactForm.scss
- client/src/styles/Nav.scss
- client/src/styles/UpcomingEvent.scss
This turned out to be more than I thought. I went a bunch of different ways but finally settled with the current way and I like it.
The nav Component has a state value that is passed as props to the HomeLinks component since we can't use navLinks for the home page links.
I deconstruct the state and setState from props, use the state value in a ternary to set active class for each link and use the setState function to update the state.
Now you might be thinking why not just have that state value live in the HomeLinks. I initially had it there but the clicking on the logo was causing some issues. I needed the logo to update the state but that state value was living in the HomeLinks component. I moved it to the Nav Component and now we have the ability to pass that state value as props down …
> [COD-27] Nav Refactor

- client/src/components/ContactForm.js
changed class to className in contact-form, fixed issue #33
> [issue #33] changed class to className in contact-form

- client/package-lock.json
- client/package.json
- client/src/assets/images/button-down.svg
- client/src/assets/images/button-up.svg
- client/src/components/utilities/Timer.js
- client/src/styles/Timer.scss
1. Start button disabled if no time is input
2. styled with 98.css (npm package)
3. Added up and down arrow buttons to increase and decrease timer input
4. alerts added for help and 'x' button
> [COD-23] Timer Styles

- client/src/components/nav/HomeLinks.js
Fixes [COD-32]
- Updated function to have the correct arguments.  It was passing a string of 'about' when we don't need to.
> [COD-32] updated handleNavClick to have correct arguments

- client/src/components/App.js
- client/src/components/ContactForm.js
- client/src/components/Home.js
- client/src/components/utilities/Modal.js
- client/src/contexts/ModalContext.js
- client/src/helpers/Modal.js
- client/src/providers/ModalProvider.js
- client/src/styles/Main.scss
- client/src/styles/Modal.scss
[COD-30]
- Created 2 new folders in client -- Contexts && Providers
- Created a context and provider for the alert modal
- Created the modal component and styled it
- Triggering the modal in the form on either successful submission or a failed submission
> [COD-30] Modal

- client/src/components/About.js
- client/src/components/Home.js
Fixes [COD-36]
- Removed container class inside the About.js file
- Moved About component inside the container div inside the Home.js file
- The look should be the exact same, I moved these to make it easier to navigate the html tree.
> [COD-36] Removed container class moved About component

- client/src/components/App.js
- client/src/components/Home.js
- client/src/components/utilities/Randomizer.js
- client/src/styles/Randomizer.scss
Fixes issue# or [COD-#]
- Fixed height of the randomizer
- Fixed the padding making the randomizer content sit behind nav 30px
- Aligned randomizer to the center of the screen
> [COD-34] Fixed basic styles for the randomizer

- client/src/components/NoMatch.js
- client/src/styles/NoMatch.scss
Fixes [COD-43]
- Changed class to className to fix error
- Added some classNames to the anchor and image to have non-global styles
> [COD-43] Fixed class to className and made anchor and img styles not global

- client/src/components/Utilities.js
- client/src/styles/Utilities.scss
Fixes [COD-44]
- Added some style to the utilities page for a quick fix.  Might not be the final look but it looks better than no styles.
[Quick Utilities Landing Page Styles](https://app.gitkraken.com/glo/card/162b23431d7c4462af9d3c04bf65132a)
> [COD-44] Added some quick styles to utilities page for a better look

- client/src/components/HomeHero.js
- client/src/components/UpcomingEvents.js
[COD-53]
- Meetup day changed to tuesday in UpcomingEvents Component
- Added MST next to the time of the meetup in UpcomingEvents Component
[Change Calendar Date To Tuesday](https://app.gitkraken.com/glo/card/dfc3d646e8a64216bc496bd726afb8f0)
> [COD-53] Changed date to tuesday in UpcomingEvents Component

- client/package-lock.json
- client/package.json
Ran into an issue with `immer` needing to be bumped and decided to see how everything worked on latest and it all worked out.
> Update all packages to latest versions

- mail-server/package-lock.json
- mail-server/package.json
- mail-server/routes/sendToMe.js
fixes #65 I added the googleapis package and refactored the code to be more aligned with some of the docs mentioned in previous messages.  I have tested locally and on Heroku.  I still have google API setup in test mode.  I will need to do some more research on how and why to take it out of that mode.
> Fix issue#65, add googleapis package

- client/package-lock.json
- client/package.json
> Update react-scripts to version 4.0.3

- client/src/components/About.js
- client/src/components/App.js
- client/src/components/ContactForm.js
- client/src/components/Home.js
- client/src/components/HomeHero.js
- client/src/components/NoMatch.js
- client/src/components/UpcomingEvents.js
- client/src/components/Utilities.js
- client/src/components/nav/HomeLinks.js
- client/src/components/nav/Nav.js
- client/src/components/nav/UtilitiesLinks.js
- client/src/components/utilities/BigWinner.js
- client/src/components/utilities/Randomizer.js
- client/src/components/utilities/Timer.js
- client/src/contexts/ModalContext.js
- client/src/helpers/Modal.js
- client/src/helpers/api.js
- client/src/index.js
- client/src/providers/ModalProvider.js
- client/src/serviceWorker.js
Fixes issue #71 
- I modified the arrow functions of the components containing the warning and moved the export default to the bottom 
- components include About.js, ContactForm.js, HomeHero.js, NoMatch.js, UpcomingEvents.js, Utilities.js, HomeLinks.js, UtilitiesLinks.js, BigWinner.js, Randomizer.js, Modal.js, ModalProvider.js
> Issue#71 I modified the arrow functions of the components containing the warning and moved the export default to the bottom
